IR_KEYWORD_ANY = "<IR_ANY>"
IR_KEYWORD_ANY_IPV4 = "<IR_ANY_IPV4>"
IR_KEYWORD_ANY_IPV6 = "<IR_ANY_IPV6>"
IR_KEYWORD_DYNAMIC = "<IR_DYNAMIC>"
IR_KEYWORD_NONE = "<IR_NONE>"

UNIVERSAL_KEYWORDS = {
    IR_KEYWORD_ANY, IR_KEYWORD_ANY_IPV4, IR_KEYWORD_ANY_IPV6,
    IR_KEYWORD_DYNAMIC, IR_KEYWORD_NONE,
    "any", "all", "any4", "any6", "any-ipv4", "any-ipv6"
}
