SHEET_ORDER = (
    "Summary", "Managed Objects", "Object Groups", "Services", "Zones",
    "Interfaces", "Routes", "ACP Rules", "Inspection Policies", "NAT Rules",
    "RA VPN Policies", "RA Connection Profiles", "RA Group Policies", "RA Address Pools",
    "RA Certificates", "RA Certificate Maps", "RA Secure Client", "RA IPsec Settings",
    "RA Address Assignment", "Native Sources", "Source Evidence", "Validation",
)

SHEET_HEADERS = {
    "Managed Objects": ("Name", "ID", "Type", "Value", "Description", "Address Family", "FQDN Lookup Type", "Overrides", "Source Plane"),
    "Object Groups": ("Name", "Members", "Literal Members", "Description", "Overrides", "Source Plane"),
    "Services": ("Name", "Protocol", "Port", "End Port", "ICMP Type", "ICMP Code", "Description", "Overrides", "Members", "Source Plane"),
    "Zones": ("Name", "Interfaces", "Source Plane"),
    "Interfaces": ("Name", "Type", "Address", "Zone", "Source Plane", "Derived Kind", "Derived Parent", "Explicit VLAN ID"),
    "Routes": ("Name", "Interface", "Destination", "Gateway", "SLA Monitor", "Source Plane", "Address Family", "Mask", "Normalized Destination"),
    "ACP Rules": ("Policy", "Rule", "Rule ID", "Enabled", "Position", "Section", "Category", "Action",
        "Source Zones", "Destination Zones", "Source Networks", "Destination Networks", "Source Ports", "Destination Ports",
        "Realm Users", "Users", "User Groups", "Applications", "Application Filters", "Inline Application Filters",
        "URLs", "URL Categories", "Time Range", "Intrusion Policy", "Variable Set", "File Policy",
        "Log Begin", "Log End", "Comments", "Source Plane", "Source Context"),
    "NAT Rules": ("Policy", "Rule", "Rule ID", "Rule Type", "Enabled", "Section", "Position",
        "Source Interface", "Destination Interface", "Original Source", "Translated Source",
        "Original Destination", "Translated Destination", "Original Source Service", "Translated Source Service",
        "Original Destination Service", "Translated Destination Service", "NAT Type", "Interface PAT",
          "DNS", "Route Lookup", "Proxy ARP", "Source Plane", "Source Context", "Additional Settings",
          "FDM Service", "Source Translation Mode", "Destination Translation Mode"),
    "Inspection Policies": ("Policy Type", "Policy", "Policy ID", "Rule", "Rule ID", "Rules Collection",
        "Position", "Collection Order", "Enabled", "Action", "Conditions and Settings", "Policy Behavior",
        "Additional Settings", "Source Plane", "Source Context"),
    "RA VPN Policies": ("Name", "ID", "Target Devices", "Access Interfaces", "Certificates",
        "Certificate Maps", "Certificate Map Settings", "Connection Profiles", "Group Policies", "Address Pools", "Realms",
        "SSL/TLS", "DTLS", "Session Settings", "Additional Settings"),
    "RA Connection Profiles": ("Policy", "Name", "ID", "Alias", "Group URL", "Enabled",
        "Authentication Method", "Realm", "Authentication Server", "Authorization Server",
        "Accounting Server", "Default Group Policy", "Address Pools", "Address Assignment",
        "Certificates", "Certificate Maps", "Connection Settings", "Additional Settings"),
    "RA Group Policies": ("Name", "ID", "VPN Access", "Protocols", "Connection Settings",
        "DNS", "WINS", "Domain", "Realm", "AAA Server Group", "Address Pools",
        "Split Tunnel Policy", "Split Tunnel Networks", "Split Tunnel ACL", "Split DNS", "Secure Client",
        "Session Settings", "Simultaneous Logins", "Additional Settings"),
    "RA Address Pools": ("Name", "ID", "Address Family", "Start", "End", "Source Representation",
        "Address Reuse Delay", "Overrides", "Additional Settings"),
    "RA Certificates": ("Name", "ID", "Type", "Issuer", "Subject", "Validity",
        "Metadata", "Private Key Present", "Additional Settings"),
    "RA Certificate Maps": ("Name", "ID", "Conditions", "Connection Profile", "Group Policy", "Additional Settings"),
    "RA Secure Client": ("Name", "ID", "Packages", "Profiles", "Additional Settings"),
    "RA IPsec Settings": ("Policy ID", "Policy Name", "Name", "IKEv2 Settings", "IPsec Settings",
        "NAT Keepalive", "Additional Settings"),
    "RA Address Assignment": ("Policy ID", "Policy Name", "Name", "Address Pools", "Assignment Method",
        "Reuse Delay", "Use DHCP", "Use Authorization Server IPv4", "Use Authorization Server IPv6",
        "Use Internal Pool IPv4", "Use Internal Pool IPv6", "Additional Settings"),
    "Source Evidence": ("Path", "Reason"),
    "Native Sources": ("Collection", "Name", "ID", "Source Context", "Source Attributes", "Raw Source"),
    "Validation": ("Severity", "Category", "Message", "Source Plane", "Object"),
}
