domain: application
part: 1
parts: 1
sections:
- path: application custom
  mode: table
  key: <tag>
  fields:
    behavior: opaque-user
    category: integer
    comment: string
    id: integer
    protocol: opaque-user
    signature: var-string
    technology: opaque-user
    vendor: opaque-user
- path: application group
  mode: table
  key: <name>
  fields:
    application: identifier-list
    behavior: opaque-user
    category: identifier-list
    comment: var-string
    popularity: option-list
    protocols: opaque-user
    risk: identifier-list
    technology: opaque-user
    type: enum
    vendor: opaque-user
- path: application list
  mode: table
  key: <name>
  fields:
    app-replacemsg: enum
    comment: var-string
    control-default-network-services: enum
    deep-app-inspection: enum
    enforce-default-app-port: enum
    extended-log: enum
    force-inclusion-ssl-di-sigs: enum
    options: option-list
    other-application-action: enum
    other-application-log: enum
    p2p-block-list: option-list
    replacemsg-group: string
    unknown-application-action: enum
    unknown-application-log: enum
  nested:
  - name: default-network-services
    mode: table
    key: <id>
    fields:
      port: integer
      services: option-list
      violation-action: enum
  - name: entries
    mode: table
    key: <id>
    fields:
      action: enum
      application: identifier-list
      behavior: opaque-user
      category: identifier-list
      exclusion: identifier-list
      log: enum
      log-packet: enum
      per-ip-shaper: string
      popularity: option-list
      protocols: opaque-user
      quarantine: enum
      quarantine-expiry: opaque-user
      quarantine-log: enum
      rate-count: integer
      rate-duration: integer
      rate-mode: enum
      rate-track: enum
      risk: identifier-list
      session-ttl: integer
      shaper: string
      shaper-reverse: string
      technology: opaque-user
      vendor: opaque-user
    nested:
    - name: parameters
      mode: table
      key: <id>
      nested:
      - name: members
        mode: table
        key: <id>
        fields:
          name: string
          value: string
- path: application name
  mode: table
  key: <name>
  fields:
    behavior: opaque-user
    category: integer
    id: integer
    popularity: integer
    protocol: opaque-user
    risk: integer
    technology: opaque-user
    vendor: opaque-user
    weight: integer
  nested:
  - name: metadata
    mode: table
    key: <id>
    fields:
      metaid: integer
      valueid: integer
  - name: parameters
    mode: table
    key: <name>
    fields:
      default: raw
  read_only: true
- path: application rule-settings
  mode: table
  key: <id>
  read_only: true
