from typing import List, Set
from fwmigrate.ir.core import IRConfig, IRAddress, IRAddressGroup, IRService, IRPolicy
from fwmigrate.ir.enums import AddressType, ServiceProtocol, PolicyAction
from fwmigrate.ir.semantics import (
    AddressUniversalFamily,
    classify_universal_address_reference,
    unsafe_zone_names,
    policy_references_unsafe_zone,
)
from fwmigrate.generators.target_helpers import allocate_target_helper_name


class CheckPointCLIGenerator:
    """Generates Check Point mgmt_cli automation batch scripts from Canonical IR."""

    def generate(self, ir: IRConfig) -> str:
        lines: List[str] = [
            "#!/bin/bash",
            "# =============================================================================",
            f"# Check Point mgmt_cli Provisioning Script for {ir.metadata.hostname or 'cp-gateway'}",
            "# Generated automatically by Universal Firewall Migration Platform",
            "# =============================================================================",
            "",
            "# Log in to Check Point Management Server",
            'SESSION_ID=$(mgmt_cli -r true login --format json | jq -r .sid)',
            'export MGMT_CLI_SESSION_ID=$SESSION_ID',
            ""
        ]

        # Determine deterministic helper object names with collision avoidance
        existing_objects = {a.name: a.value for a in ir.addresses}

        ipv4_helper_name, ipv4_reused = allocate_target_helper_name(
            "__fwmigrate_any_ipv4", existing_objects, "0.0.0.0/0"
        )

        ipv6_helper_name, ipv6_reused = allocate_target_helper_name(
            "__fwmigrate_any_ipv6", existing_objects, "::/0"
        )

        needed_helpers: Set[str] = set()
        unsafe_zones = unsafe_zone_names(ir)

        # Pre-scan policies to know which helpers are needed
        for pol in ir.policies:
            if not pol.safe_for_target_generation or policy_references_unsafe_zone(pol, unsafe_zones):
                continue
            for s in (pol.source or []):
                fam = classify_universal_address_reference(s)
                if fam == AddressUniversalFamily.IPV4:
                    needed_helpers.add("ipv4")
                elif fam == AddressUniversalFamily.IPV6:
                    needed_helpers.add("ipv6")
            for d in (pol.destination or []):
                fam = classify_universal_address_reference(d)
                if fam == AddressUniversalFamily.IPV4:
                    needed_helpers.add("ipv4")
                elif fam == AddressUniversalFamily.IPV6:
                    needed_helpers.add("ipv6")

        # 1. Address Objects
        if ir.addresses or needed_helpers:
            lines.append("# --- Network Objects ---")
            if "ipv4" in needed_helpers and not ipv4_reused:
                lines.append(f'mgmt_cli add network name "{ipv4_helper_name}" subnet4 "0.0.0.0" mask-length4 0 comments "Universal IPv4 helper generated by firewall-migration-tool" --session-id $SESSION_ID -s id.txt')
            if "ipv6" in needed_helpers and not ipv6_reused:
                lines.append(f'mgmt_cli add network name "{ipv6_helper_name}" subnet6 "::" mask-length6 0 comments "Universal IPv6 helper generated by firewall-migration-tool" --session-id $SESSION_ID -s id.txt')

            for addr in ir.addresses:
                comments_arg = f' comments "{addr.description}"' if addr.description else ""
                if addr.type == AddressType.HOST:
                    ip = addr.value.split('/')[0]
                    lines.append(f'mgmt_cli add host name "{addr.name}" ip-address "{ip}"{comments_arg} --session-id $SESSION_ID -s id.txt')
                elif addr.type == AddressType.NETWORK:
                    if '/' in addr.value:
                        ip, prefix = addr.value.split('/')
                        lines.append(f'mgmt_cli add network name "{addr.name}" subnet "{ip}" mask-length {prefix}{comments_arg} --session-id $SESSION_ID -s id.txt')
                    elif ' ' in addr.value:
                        ip, mask = addr.value.split(' ')
                        lines.append(f'mgmt_cli add network name "{addr.name}" subnet "{ip}" subnet-mask "{mask}"{comments_arg} --session-id $SESSION_ID -s id.txt')
                elif addr.type == AddressType.RANGE:
                    parts = addr.value.replace(' ', '-').split('-')
                    if len(parts) == 2:
                        lines.append(f'mgmt_cli add address-range name "{addr.name}" ip-address-first "{parts[0]}" ip-address-last "{parts[1]}"{comments_arg} --session-id $SESSION_ID -s id.txt')
                elif addr.type == AddressType.STUB_UNSUPPORTED:
                    lines.append(f'# Address "{addr.name}" withheld: unsupported source address semantics require manual review')
                elif addr.type == AddressType.DYNAMIC:
                    lines.append(f'mgmt_cli add dynamic-object name "{addr.name}"{comments_arg} --session-id $SESSION_ID -s id.txt')
            lines.append("")

        # 2. Address Groups
        if ir.address_groups:
            lines.append("# --- Group Objects ---")
            for grp in ir.address_groups:
                if grp.requires_manual_review:
                    continue
                if grp.is_dynamic:
                    lines.append(f'mgmt_cli add dynamic-object name "{grp.name}" --session-id $SESSION_ID -s id.txt')
                else:
                    members_args = " ".join([f'members.{i+1} "{m}"' for i, m in enumerate(grp.members)])
                    lines.append(f'mgmt_cli add group name "{grp.name}" {members_args} --session-id $SESSION_ID -s id.txt')
            lines.append("")

        # 3. Services
        if ir.services:
            lines.append("# --- Service Objects ---")
            for svc in ir.services:
                if (
                    svc.requires_manual_review
                    or any(port.source_port for port in svc.ports)
                ):
                    lines.append(
                        f"# Service {svc.name} withheld: source/proxy port semantics require manual review"
                    )
                    continue
                for port_entry in svc.ports:
                    proto = port_entry.protocol.value.lower()
                    if proto == 'tcp':
                        lines.append(f'mgmt_cli add service-tcp name "{svc.name}" port "{port_entry.port}" --session-id $SESSION_ID -s id.txt')
                    elif proto == 'udp':
                        lines.append(f'mgmt_cli add service-udp name "{svc.name}" port "{port_entry.port}" --session-id $SESSION_ID -s id.txt')
            lines.append("")

        # 4. Security Rules
        if ir.policies:
            lines.append("# --- Access Rulebase ---")
            for idx, pol in enumerate(ir.policies):
                if (
                    pol.action == PolicyAction.IPSEC
                    or not pol.safe_for_target_generation
                    or pol.source_user_groups
                    or pol.source_users
                ):
                    lines.append(
                        f"# Policy {pol.name} withheld: source semantics require manual review"
                    )
                    continue
                if policy_references_unsafe_zone(pol, unsafe_zones):
                    lines.append(
                        f"# Policy {pol.name} withheld: referenced zone requires manual review"
                    )
                    continue
                act = "Accept" if pol.action == PolicyAction.ALLOW else "Drop"

                # Source mapping
                src_raw = pol.source[0] if pol.source else "any"
                src_fam = classify_universal_address_reference(src_raw)
                if src_fam == AddressUniversalFamily.IPV4:
                    src_val = ipv4_helper_name
                elif src_fam == AddressUniversalFamily.IPV6:
                    src_val = ipv6_helper_name
                elif src_fam == AddressUniversalFamily.ANY:
                    src_val = "Any"
                else:
                    src_val = src_raw

                # Destination mapping
                dst_raw = pol.destination[0] if pol.destination else "any"
                dst_fam = classify_universal_address_reference(dst_raw)
                if dst_fam == AddressUniversalFamily.IPV4:
                    dst_val = ipv4_helper_name
                elif dst_fam == AddressUniversalFamily.IPV6:
                    dst_val = ipv6_helper_name
                elif dst_fam == AddressUniversalFamily.ANY:
                    dst_val = "Any"
                else:
                    dst_val = dst_raw

                svc_val = pol.service[0] if pol.service and pol.service[0].lower() not in ("all", "any") else "Any"

                lines.append(f'mgmt_cli add access-rule layer "Network" position {idx+1} name "{pol.name}" source "{src_val}" destination "{dst_val}" service "{svc_val}" action "{act}" --session-id $SESSION_ID -s id.txt')

            # 4.5 Threat Prevention Rules
            threat_policies = [
                p for p in ir.policies
                if p.safe_for_target_generation
                and not policy_references_unsafe_zone(p, unsafe_zones)
                and not p.source_user_groups
                and not p.source_users
                and p.action != PolicyAction.IPSEC
                and (p.security_profile_group or p.antivirus or p.ips_sensor)
            ]
            if threat_policies:
                lines.append("")
                lines.append("# --- Threat Prevention Layer ---")
                for idx, pol in enumerate(threat_policies):
                    profile_name = pol.security_profile_group or "Optimized"
                    lines.append(f'mgmt_cli add threat-rule layer "Standard Threat Prevention" position {idx+1} name "Threat_{pol.name}" action "Apply" profile "{profile_name}" --session-id $SESSION_ID -s id.txt')
            lines.append("")

        lines.append("# Publish changes and logout")
        lines.append("mgmt_cli publish --session-id $SESSION_ID -s id.txt")
        lines.append("mgmt_cli logout --session-id $SESSION_ID -s id.txt")
        lines.append("")

        return "\n".join(lines)
