SHEET_ORDER = (
    "Summary", "Review Required", "Validation", "Source Inventory", "Extraction Coverage",
    "Unsupported Source", "Unresolved References", "Additional Settings", "Interfaces", "Zones",
    "Routing Instances", "Address Books", "Applications", "Policies", "NAT", "VPN",
    "DHCP Local Servers", "DHCP Pools", "Access Profiles", "Firewall Users", "APBR", "Remote Access",
    "Policy Relationships", "NAT Usage", "NAT Pool Usage", "VPN Relationships", "Secure Connect",
    "APBR Relationships", "Inheritance",
)

SHEET_HEADERS = {
    "Interfaces": ("Context", "Interface", "Unit", "Parent", "Name", "Interface Type", "Source Present",
                    "Aggregate Parent", "Aggregate Parent Resolved", "Redundant Parent", "Redundant Parent Resolved",
                    "Aggregate Members", "Redundant Members", "Zone Memberships", "Routing Instance Memberships"),
    "Zones": ("Context", "Zone", "Interface"),
    "Routing Instances": ("Context", "Name", "Interfaces"),
    "Address Books": ("Context", "Name", "Zones", "Addresses", "Address Sets"),
    "Applications": ("Context", "Name", "Terms"),
    "Policies": ("Context", "Name", "Order", "From Zones", "To Zones"),
    "NAT": ("Context", "Type", "Name", "Rules"),
    "VPN": ("Context", "Type", "Name"),
    "DHCP Local Servers": ("Context", "Name", "Routing Instance", "Family", "Interface"),
    "DHCP Pools": ("Context", "Name", "Routing Instance", "Family", "Linked Pool", "Ranges", "Hosts", "Router", "Name Servers"),
    "Access Profiles": ("Context", "Name", "Clients"),
    "Firewall Users": ("Context", "Access Profile", "Name", "Password Configured", "Client Groups"),
    "APBR": ("Context", "Kind", "Name"),
    "Remote Access": ("Context", "Kind", "Name", "Access Profile", "Client Config", "IPsec VPN", "Multi Access", "Application Bypass Terms"),
    "Policy Relationships": ("Context", "Policy Scope", "From Zone", "To Zone", "Name", "Order", "Source Identities"),
    "NAT Usage": ("Context", "NAT Type", "Rule Set Name", "Rule Name", "Rule Order", "Action Type", "Pool Name", "Pool Resolved", "Address References"),
    "NAT Pool Usage": ("Context", "NAT Type", "Pool Name", "Rule Set Name", "Rule Name", "Resolved"),
    "VPN Relationships": ("Context", "Source Type", "Source Name", "Relationship", "Target Type", "Target Name", "Resolved"),
    "Secure Connect": ("Context", "Source Type", "Source Name", "Relationship", "Target Type", "Target Name", "Resolved", "Interface"),
    "APBR Relationships": ("Context", "Source Type", "Source Name", "Relationship", "Target Type", "Target Name", "Resolved"),
    "Inheritance": ("Record Type", "Context", "Origin", "Status", "Target Path", "Source Path", "Source Group", "Group Chain", "Source Order", "Active", "Value"),
    "Review Required": ("Severity", "Code", "Category", "Message", "Context", "Source Path", "Object", "Field"),
    "Validation": ("Code", "Severity", "Category", "Message", "Context Type", "Context", "Source Path", "Object Type", "Object", "Field", "Reference", "Expected Type"),
    "Extraction Coverage": ("Context", "Source Path", "Source Commands", "Extracted", "Partial", "Source Only", "Unsupported", "Unknown", "Ignored", "Parse Errors", "Unresolved References", "Status", "Review Required"),
    "Unsupported Source": ("Context", "Source Path", "Source Name", "Reason", "Raw Capture"),
    "Unresolved References": ("Context Type", "Context", "Source Path", "Source Object", "Source Field", "Reference", "Expected Type", "Resolution", "Reason"),
    "Additional Settings": ("Context", "Object Type", "Object", "Setting", "Value"),
}
