SHEET_ORDER = (
    "Summary", "Review Required", "Validation", "Source Inventory", "Extraction Coverage",
    "Unsupported Source", "Unresolved References", "Additional Settings",
    "Interfaces", "Zones", "Routing Instances",
    "Address Books", "Addresses", "Address Sets",
    "Applications", "Application Sets", "Schedulers",
    "Policies", "Policy Details",
    "NAT", "NAT Pools", "NAT Rules",
    "VPN", "IKE Proposals", "IKE Policies", "IKE Gateways",
    "IPsec Proposals", "IPsec Policies", "IPsec VPNs", "Traffic Selectors",
    "Static Routes",
    "DHCP Local Servers", "DHCP Relay Groups", "DHCP Pools",
    "Access Profiles", "Firewall Users", "APBR", "Remote Access",
    "Policy Relationships", "Policy Reference Relationships",
    "NAT Usage", "NAT Pool Usage", "VPN Relationships", "Secure Connect",
    "APBR Relationships", "Inheritance",
)

SHEET_HEADERS = {
    "Interfaces": ("Context", "Interface", "Unit", "Parent", "Name", "Interface Type", "Source Present",
                    "Aggregate Parent", "Aggregate Parent Resolved", "Redundant Parent", "Redundant Parent Resolved",
                    "Aggregate Members", "Redundant Members", "Zone Memberships", "Routing Instance Memberships"),
    "Zones": ("Context", "Zone", "Interface"),
    "Routing Instances": ("Context", "Name", "Interfaces"),
    "Address Books": ("Context", "Name", "Zones", "Addresses", "Address Sets"),
    "Addresses": ("Context", "Address Book", "Name", "Type", "Prefix", "FQDN", "Range Start", "Range End",
                  "Wildcard", "Zone", "Description"),
    "Address Sets": ("Context", "Address Book", "Name", "Members", "Member Types", "Zone", "Description"),
    "Applications": ("Context", "Name", "Terms"),
    "Application Sets": ("Context", "Name", "Applications", "Description"),
    "Schedulers": ("Context", "Name", "Start Date", "Stop Date", "Daily", "Weekdays",
                   "Daily Windows", "Weekday Windows", "Exclusions", "Description"),
    "Policies": ("Context", "Policy Scope", "From Zone", "To Zone", "Name", "Order"),
    "Policy Details": ("Context", "Policy Scope", "Name", "Order", "From Zones", "To Zones",
                       "Source Addresses", "Destination Addresses", "Applications", "Dynamic Applications",
                       "Source Identities", "Scheduler", "Action", "Log Session Init", "Log Session Close",
                       "Application Services", "Security Profile References", "Description"),
    "NAT": ("Context", "Type", "Name", "Rules"),
    "NAT Pools": ("Context", "NAT Type", "Name", "Routing Instance", "Addresses", "Address Ranges", "Ports", "Options"),
    "NAT Rules": ("Context", "NAT Type", "Rule Set", "Rule", "Order",
                  "From Zones", "From Interfaces", "From Routing Instances",
                  "To Zones", "To Interfaces", "To Routing Instances",
                  "Source Addresses", "Destination Addresses", "Source Address Names", "Destination Address Names",
                  "Source Ports", "Destination Ports", "Protocols", "Applications", "Action", "Disabled", "Description"),
    "VPN": ("Context", "Type", "Name"),
    "IKE Proposals": ("Context", "Name", "Authentication Method", "DH Group", "Authentication Algorithm",
                      "Encryption Algorithm", "Digital Signature Scheme", "PRF Algorithm",
                      "Signature Hash Algorithm", "Lifetime Seconds", "Description"),
    "IKE Policies": ("Context", "Name", "Mode", "Proposal Set", "Proposals", "Pre Shared Key Configured",
                     "Certificate Reference", "Local Certificate"),
    "IKE Gateways": ("Context", "Name", "IKE Policy", "Address", "External Interface", "Version",
                     "Local Address", "Local Identity", "Remote Identity", "NAT Traversal", "DPD",
                     "Certificate Reference"),
    "IPsec Proposals": ("Context", "Name", "Protocol", "Authentication Algorithm", "Encryption Algorithm",
                        "Lifetime Seconds", "Lifetime Kilobytes", "Description"),
    "IPsec Policies": ("Context", "Name", "Proposal Set", "Proposals", "PFS Group"),
    "IPsec VPNs": ("Context", "Name", "Bind Interface", "IKE Gateway", "IPsec Policy", "Establish Tunnels",
                   "VPN Monitor Destination", "VPN Monitor Source Interface"),
    "Traffic Selectors": ("Context", "VPN", "Name", "Term", "Local IP", "Remote IP", "Protocol",
                          "Local Port", "Remote Port"),
    "Static Routes": ("Context", "Routing Instance", "RIB", "Destination", "Next Hop", "Qualified",
                      "Next Table", "Route Preference", "Route Metric", "Route Tag",
                      "Next Hop Preference", "Next Hop Metric", "Next Hop Tag",
                      "Action", "Retain", "Installation", "Disabled"),
    "DHCP Local Servers": ("Context", "Name", "Routing Instance", "Family", "Interface"),
    "DHCP Relay Groups": ("Context", "Name", "Routing Instance", "Interfaces", "Server Groups"),
    "DHCP Pools": ("Context", "Name", "Routing Instance", "Family", "Linked Pool", "Ranges", "Hosts", "Router", "Name Servers"),
    "Access Profiles": ("Context", "Name", "Clients"),
    "Firewall Users": ("Context", "Access Profile", "Name", "Password Configured", "Client Groups"),
    "APBR": ("Context", "Kind", "Name"),
    "Remote Access": ("Context", "Kind", "Name", "Access Profile", "Client Config", "IPsec VPN", "Multi Access", "Application Bypass Terms"),
    "Policy Relationships": ("Context", "Policy Scope", "From Zone", "To Zone", "Name", "Order", "Source Identities"),
    "Policy Reference Relationships": ("Context", "Policy Scope", "Source Name", "Source Field", "Relationship", "Target Type", "Target Name", "Resolved", "Source Effective", "Status"),
    "NAT Usage": ("Context", "NAT Type", "Rule Set Name", "Rule Name", "Rule Order", "Action Type", "Pool Name", "Pool Resolved", "Pool Source Effective", "Pool Status", "Address References"),
    "NAT Pool Usage": ("Context", "NAT Type", "Pool Name", "Rule Set Name", "Rule Name", "Resolved", "Source Effective", "Status"),
    "VPN Relationships": ("Context", "Source Type", "Source Name", "Relationship", "Target Type", "Target Name", "Resolved", "Source Effective", "Status"),
    "Secure Connect": ("Context", "Source Type", "Source Name", "Relationship", "Target Type", "Target Name", "Resolved", "Source Effective", "Status", "Interface"),
    "APBR Relationships": ("Context", "Source Type", "Source Name", "Relationship", "Target Type", "Target Name", "Resolved", "Source Effective", "Status"),
    "Inheritance": ("Record Type", "Context", "Origin", "Status", "Target Path", "Source Path", "Source Group", "Group Chain", "Source Order", "Active", "Value"),
    "Review Required": ("Severity", "Code", "Category", "Message", "Context", "Source Path", "Object", "Field"),
    "Validation": ("Code", "Severity", "Category", "Message", "Context Type", "Context", "Source Path", "Object Type", "Object", "Field", "Reference", "Expected Type"),
    "Extraction Coverage": ("Context", "Source Path", "Source Commands", "Extracted", "Partial", "Source Only", "Unsupported", "Unknown", "Ignored", "Parse Errors", "Unresolved References", "Status", "Review Required"),
    "Unsupported Source": ("Context", "Source Path", "Source Name", "Reason", "Raw Capture"),
    "Unresolved References": ("Context Type", "Context", "Source Path", "Source Object", "Source Field", "Reference", "Expected Type", "Resolution", "Reason"),
    "Additional Settings": ("Context", "Object Type", "Object", "Setting", "Value"),
}
